# Generated by Django 2.1.7 on 2019-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=500)),
                ('end', models.CharField(max_length=500)),
                ('vehicle', models.CharField(max_length=500)),
                ('cost', models.FloatField(max_length=500)),
                ('time', models.IntegerField(max_length=500)),
            ],
        ),
    ]
